kube-prometheus-stack:
  grafana:
    enabled: true
    service:
      type: ClusterIP
  prometheus:
    prometheusSpec:
      retention: 24h
      resources:
        requests:
          cpu: 200m
          memory: 400Mi
        limits:
          cpu: 500m
          memory: 1Gi
  alertmanager:
    enabled: false